"""
Brooklet Word — Automatic Numbering Reference
=============================================

This file is the canonical implementation pattern for Word-native
paragraph-level automatic numbering in Brooklet `.docx` outputs.

Use it whenever you build a Word document with python-docx and need any
ordered structure (Parties, Background, clauses, sub-clauses, lettered
limbs, schedule "No." columns, action items, etc.).

Why
---
Numbers must be generated by Word's list engine, not typed as literal text.
This guarantees that inserting or deleting a list item in Microsoft Word
auto-renumbers every other item.

Numbering inventory
-------------------
abstractNumId 100 -> Parties:    (1), (2), ...                       [restart per block]
abstractNumId 101 -> Background: (A), (B), (C), ...                  [restart per block]
abstractNumId 102 -> Main clauses (multilevel):
                       Lvl 0 = "1."  bold
                       Lvl 1 = "1.1"
                       Lvl 2 = "(a)" lowerLetter
                     [Lvl 0 continuous; Lvl 1/2 auto-restart on parent change]
abstractNumId 103 -> Schedule "No." column: 1., 2., 3., ...          [restart per schedule]

Bind each abstract to one (or more) `<w:num>` instances. Lists that must
restart at 1 on each reuse get a fresh `<w:num>` clone every time.
"""

from copy import deepcopy
from docx import Document
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import qn

W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
NS = f'xmlns:w="{W}"'

# -----------------------------------------------------------------------------
# 1. Bootstrap: ensure the numbering part exists, then install Brooklet definitions
# -----------------------------------------------------------------------------

def install_brooklet_numbering(doc):
    """
    Install the four Brooklet abstract numbering definitions and their default
    bindings into doc's numbering.xml. Call this once, immediately after
    creating the Document.

    Returns a dict with the default numIds:
        {
          "parties_default":   <numId for abstractNum 100>,   # use new_parties_numid()
          "background_default":<numId for abstractNum 101>,   # use new_background_numid()
          "main":              <numId for abstractNum 102>,   # reuse throughout document
          "schedule_default":  <numId for abstractNum 103>,   # use new_schedule_numid()
        }
    """
    # Trigger creation of numbering.xml by briefly adding a List Number paragraph
    tmp = doc.add_paragraph("tmp", style="List Number")
    numbering_part = doc.part.numbering_part
    tmp._element.getparent().remove(tmp._element)

    numbering_xml = f"""<w:numbering {NS}>
      <!-- ABSTRACT 100: Parties (1), (2), ... -->
      <w:abstractNum w:abstractNumId="100">
        <w:multiLevelType w:val="singleLevel"/>
        <w:lvl w:ilvl="0">
          <w:start w:val="1"/>
          <w:numFmt w:val="decimal"/>
          <w:lvlText w:val="(%1)"/>
          <w:lvlJc w:val="left"/>
          <w:pPr><w:ind w:left="720" w:hanging="720"/></w:pPr>
        </w:lvl>
      </w:abstractNum>

      <!-- ABSTRACT 101: Background (A), (B), ... -->
      <w:abstractNum w:abstractNumId="101">
        <w:multiLevelType w:val="singleLevel"/>
        <w:lvl w:ilvl="0">
          <w:start w:val="1"/>
          <w:numFmt w:val="upperLetter"/>
          <w:lvlText w:val="(%1)"/>
          <w:lvlJc w:val="left"/>
          <w:pPr><w:ind w:left="720" w:hanging="720"/></w:pPr>
        </w:lvl>
      </w:abstractNum>

      <!-- ABSTRACT 102: Main clauses (1., 1.1, (a)) -->
      <w:abstractNum w:abstractNumId="102">
        <w:multiLevelType w:val="multilevel"/>
        <w:lvl w:ilvl="0">
          <w:start w:val="1"/>
          <w:numFmt w:val="decimal"/>
          <w:lvlText w:val="%1."/>
          <w:lvlJc w:val="left"/>
          <w:pPr><w:ind w:left="0" w:hanging="0"/></w:pPr>
          <w:rPr><w:b/></w:rPr>
        </w:lvl>
        <w:lvl w:ilvl="1">
          <w:start w:val="1"/>
          <w:numFmt w:val="decimal"/>
          <w:lvlText w:val="%1.%2"/>
          <w:lvlJc w:val="left"/>
          <w:pPr><w:ind w:left="567" w:hanging="567"/></w:pPr>
        </w:lvl>
        <w:lvl w:ilvl="2">
          <w:start w:val="1"/>
          <w:numFmt w:val="lowerLetter"/>
          <w:lvlText w:val="(%3)"/>
          <w:lvlJc w:val="left"/>
          <w:pPr><w:ind w:left="1134" w:hanging="567"/></w:pPr>
        </w:lvl>
      </w:abstractNum>

      <!-- ABSTRACT 103: Schedule "No." column 1., 2., 3., ... -->
      <w:abstractNum w:abstractNumId="103">
        <w:multiLevelType w:val="singleLevel"/>
        <w:lvl w:ilvl="0">
          <w:start w:val="1"/>
          <w:numFmt w:val="decimal"/>
          <w:lvlText w:val="%1."/>
          <w:lvlJc w:val="left"/>
          <w:pPr><w:ind w:left="0" w:hanging="0"/></w:pPr>
        </w:lvl>
      </w:abstractNum>

      <!-- Default <w:num> bindings -->
      <w:num w:numId="10"><w:abstractNumId w:val="100"/></w:num>
      <w:num w:numId="11"><w:abstractNumId w:val="101"/></w:num>
      <w:num w:numId="12"><w:abstractNumId w:val="102"/></w:num>
      <w:num w:numId="13"><w:abstractNumId w:val="103"/></w:num>
    </w:numbering>"""

    new_root = parse_xml(numbering_xml)
    numbering_part._element.clear()
    for k, v in new_root.attrib.items():
        numbering_part._element.set(k, v)
    for child in list(new_root):
        numbering_part._element.append(child)

    return {
        "parties_default": 10,
        "background_default": 11,
        "main": 12,
        "schedule_default": 13,
    }


# -----------------------------------------------------------------------------
# 2. Helpers to clone a <w:num> with restart-at-1, and to attach numbering
# -----------------------------------------------------------------------------

def _clone_num_with_restart(doc, abstract_num_id):
    """
    Create a new <w:num> bound to `abstract_num_id` with a startOverride at 1
    on level 0. Returns the new numId.

    Use this every time a list block (Parties, Background, Schedule) appears
    so it restarts at 1 / A.
    """
    numbering_part = doc.part.numbering_part
    root = numbering_part._element
    used = [int(n.get(qn("w:numId"))) for n in root.findall(qn("w:num"))]
    new_id = (max(used) if used else 0) + 1

    new_num = OxmlElement("w:num")
    new_num.set(qn("w:numId"), str(new_id))
    abs_ref = OxmlElement("w:abstractNumId")
    abs_ref.set(qn("w:val"), str(abstract_num_id))
    new_num.append(abs_ref)

    lvl_override = OxmlElement("w:lvlOverride")
    lvl_override.set(qn("w:ilvl"), "0")
    start_override = OxmlElement("w:startOverride")
    start_override.set(qn("w:val"), "1")
    lvl_override.append(start_override)
    new_num.append(lvl_override)

    root.append(new_num)
    return new_id


def new_parties_numid(doc):
    """Fresh restart-at-1 numId for a Parties block."""
    return _clone_num_with_restart(doc, 100)


def new_background_numid(doc):
    """Fresh restart-at-1 numId for a Background block."""
    return _clone_num_with_restart(doc, 101)


def new_schedule_numid(doc):
    """Fresh restart-at-1 numId for a Schedule No. column."""
    return _clone_num_with_restart(doc, 103)


def new_note_list_numid(doc):
    """
    Fresh restart-at-1 numId for a numbered list in a Note or Memo
    (e.g., Outstanding Points, Action Items, Sources, 其他事项).
    Uses abstractNumId 103 -- renders as '1.', '2.', '3.', ...
    Call this ONCE per list block, then reuse the returned numId for
    all items within that block.
    """
    return _clone_num_with_restart(doc, 103)


def align_table_to_body(doc, table):
    """
    Align a table flush with body text margins.
    Call this on EVERY table immediately after adding it to the document.

    Performs three fixes:
    1. Sets table width to 100% of text area (w:type="pct" w:w="5000")
    2. Removes any table-level left indent (w:tblInd)
    3. Zeros out default cell left/right margins so cell text
       starts at the same horizontal position as body paragraphs.
    """
    tbl = table._tbl
    tblPr = tbl.tblPr
    if tblPr is None:
        tblPr = OxmlElement('w:tblPr')
        tbl.insert(0, tblPr)

    # 1. Remove existing tblInd (table-level indentation)
    for ind in tblPr.findall(qn('w:tblInd')):
        tblPr.remove(ind)

    # 2. Set table width to 100% of page text area
    for existing in tblPr.findall(qn('w:tblW')):
        tblPr.remove(existing)
    tblW = OxmlElement('w:tblW')
    tblW.set(qn('w:w'), '5000')     # 5000 = 100% in pct units
    tblW.set(qn('w:type'), 'pct')
    tblPr.insert(0, tblW)

    # 3. Set table alignment to left
    for existing in tblPr.findall(qn('w:jc')):
        tblPr.remove(existing)
    jc = OxmlElement('w:jc')
    jc.set(qn('w:val'), 'left')
    tblPr.append(jc)

    # 4. Zero out default cell margins (left/right)
    #    so cell text aligns with body text.
    #    Only touch left/right; preserve top/bottom if set.
    tblCellMar = tblPr.find(qn('w:tblCellMar'))
    if tblCellMar is None:
        tblCellMar = OxmlElement('w:tblCellMar')
        tblPr.append(tblCellMar)
    # Remove existing left/right margin elements
    for edge in ('left', 'right'):
        for existing in tblCellMar.findall(qn(f'w:{edge}')):
            tblCellMar.remove(existing)
    # Set left margin to 0
    left_mar = OxmlElement('w:left')
    left_mar.set(qn('w:w'), '0')
    left_mar.set(qn('w:type'), 'dxa')
    tblCellMar.append(left_mar)
    # Set right margin to 0
    right_mar = OxmlElement('w:right')
    right_mar.set(qn('w:w'), '0')
    right_mar.set(qn('w:type'), 'dxa')
    tblCellMar.append(right_mar)


def add_note_numbered_item(doc, num_id, text, bold=False, italic=False, font_name="Candara", font_size=12):
    """
    Add a single numbered item to a Note/Memo list.

    doc      : python-docx Document
    num_id   : int from new_note_list_numid()
    text     : the item text (do NOT include '1.', '2.', etc.)
    bold     : if True, entire item text is bold
    italic   : if True, entire item text is italic
    font_name: font face (default Candara)
    font_size: font size in pt (default 12)

    Returns the paragraph for further customisation.
    """
    from docx.shared import Pt
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    p = doc.add_paragraph()
    apply_numbering(p, num_id, 0)
    run = p.add_run(text)
    run.font.name = font_name
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.italic = italic
    # Set East Asian font
    rPr = run._element.get_or_add_rPr()
    rFonts = OxmlElement('w:rFonts')
    rFonts.set(qn('w:eastAsia'), font_name)
    rPr.insert(0, rFonts)
    return p


def main_numid():
    """Reuse this single numId for all main-clause paragraphs."""
    return 12


def apply_numbering(paragraph, num_id, ilvl):
    """
    Attach <w:numPr> to a paragraph so Word treats it as a list item.

    paragraph : a docx.text.paragraph.Paragraph
    num_id    : int, the numId from numbering.xml
    ilvl      : int, the level (0 for top, 1 for sub, 2 for limbs)
    """
    pPr = paragraph._p.get_or_add_pPr()
    existing = pPr.find(qn("w:numPr"))
    if existing is not None:
        pPr.remove(existing)
    numPr = OxmlElement("w:numPr")
    ilvl_el = OxmlElement("w:ilvl")
    ilvl_el.set(qn("w:val"), str(ilvl))
    numId_el = OxmlElement("w:numId")
    numId_el.set(qn("w:val"), str(num_id))
    numPr.append(ilvl_el)
    numPr.append(numId_el)
    pPr.append(numPr)


# -----------------------------------------------------------------------------
# 3. Convenience paragraph builders for the four canonical Brooklet patterns
# -----------------------------------------------------------------------------

def add_party(doc, parties_num_id, runs):
    """
    Add a numbered Party paragraph. `runs` is a list of (text, attrs) tuples
    where attrs may include {"bold": True, "italic": True}.
    Do NOT prefix the text with "(1)" / "(2)" — the list engine generates it.
    """
    p = doc.add_paragraph()
    apply_numbering(p, parties_num_id, 0)
    for text, attrs in runs:
        r = p.add_run(text)
        if attrs.get("bold"):
            r.bold = True
        if attrs.get("italic"):
            r.italic = True
    return p


def add_background(doc, background_num_id, text):
    """Add a numbered Background paragraph (renders as (A), (B), ...)."""
    p = doc.add_paragraph(text)
    apply_numbering(p, background_num_id, 0)
    return p


def add_clause_heading(doc, title, bold=True):
    """
    Add a top-level main clause heading (renders as '1.', '2.', ...).
    Pass only the title — never write '1. Title'.
    """
    p = doc.add_paragraph()
    apply_numbering(p, main_numid(), 0)
    r = p.add_run(title)
    r.bold = bold
    return p


def add_subclause(doc, text):
    """Add a sub-clause paragraph (renders as '1.1', '2.3', ...)."""
    p = doc.add_paragraph(text)
    apply_numbering(p, main_numid(), 1)
    return p


def add_limb(doc, text):
    """Add a lettered limb paragraph (renders as '(a)', '(b)', ...)."""
    p = doc.add_paragraph(text)
    apply_numbering(p, main_numid(), 2)
    return p


def add_schedule_row_no(cell, schedule_num_id):
    """
    Mark a schedule row's first cell as an auto-numbered '1.' / '2.' marker.
    Leave the cell's run text empty — the list marker IS the number.
    """
    cell.text = ""
    p = cell.paragraphs[0]
    apply_numbering(p, schedule_num_id, 0)
    return p


# -----------------------------------------------------------------------------
# 4. Minimal end-to-end usage example
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    doc = Document()
    ids = install_brooklet_numbering(doc)

    # --- Parties block (restarts at 1) -----------------------------------
    parties_id = new_parties_numid(doc)
    add_party(doc, parties_id, [
        ("Brooklet Advisory Limited", {"bold": True}),
        (", a company incorporated in Hong Kong ...", {}),
    ])
    add_party(doc, parties_id, [
        ("[COUNTERPARTY NAME]", {"bold": True}),
        (", a company incorporated in [...] ...", {}),
    ])

    # --- Background block (restarts at A) --------------------------------
    bg_id = new_background_numid(doc)
    add_background(doc, bg_id, "First recital ...")
    add_background(doc, bg_id, "Second recital ...")
    add_background(doc, bg_id, "Third recital ...")

    # --- Operative clauses (continuous 1., 2., 3., ... at Lvl 0) ---------
    add_clause_heading(doc, "Interpretation")
    add_subclause(doc, "The following definitions apply ...")
    add_subclause(doc, "Headings shall not affect interpretation ...")

    add_clause_heading(doc, "Term and Termination")
    add_subclause(doc, "This Agreement commences on ...")
    add_subclause(doc, "Either Party may terminate by giving notice if:")
    add_limb(doc, "the other commits a material breach;")
    add_limb(doc, "the other becomes insolvent; or")
    add_limb(doc, "regulatory action is taken against the other.")

    # --- Schedule No. column (restarts at 1) -----------------------------
    sch_id = new_schedule_numid(doc)
    table = doc.add_table(rows=4, cols=2)
    table.style = "Table Grid"
    table.rows[0].cells[0].text = "No."
    table.rows[0].cells[1].text = "Detail"
    for i in range(1, 4):
        add_schedule_row_no(table.rows[i].cells[0], sch_id)

    doc.save("brooklet_autonumbering_example.docx")
